package main

const uiHTML = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>HarnessTalkie</title>
<style>
body{font:16px system-ui;max-width:1000px;margin:2rem auto;padding:0 1rem;background:#f5f7fb;color:#182230}
main{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.card{background:#fff;padding:1rem;border-radius:12px;box-shadow:0 1px 4px #ccd}
input,textarea,button{font:inherit;padding:.55rem;margin:.2rem 0;border:1px solid #ccd;border-radius:6px}input,textarea{width:calc(100% - 1.3rem)}textarea{min-height:3rem}button{background:#2357d9;color:#fff;cursor:pointer}.wide{grid-column:1/-1}.content{min-height:2rem;white-space:pre-wrap}.status{color:#52606d}
</style></head><body><h1>HarnessTalkie</h1><p class="status" id="status">Load an identity to begin.</p><main>
<section class="card"><h2>Identity</h2><input id="identity-id" data-testid="identity-id" placeholder="identity name or id"><button id="identity-load" data-testid="identity-load">Load identity</button><div data-testid="presence" class="content"></div></section>
<section class="card"><h2>Direct message</h2><input id="dm-recipient" data-testid="dm-recipient" placeholder="recipient id"><textarea id="dm-content" data-testid="dm-content" placeholder="message"></textarea><button id="dm-send" data-testid="dm-send">Send DM</button><div data-testid="dm-messages" class="content"></div></section>
<section class="card"><h2>Group</h2><input id="group-name" data-testid="group-name" placeholder="new group name"><button id="group-create" data-testid="group-create">Create group</button><input id="group-id" data-testid="group-id" placeholder="group id"><textarea id="group-message" data-testid="group-message" placeholder="group message"></textarea><button id="group-send" data-testid="group-send">Send group message</button><div data-testid="group-messages" class="content"></div></section>
<section class="card"><h2>Posts</h2><input id="post-title" data-testid="post-title" placeholder="title"><textarea id="post-content" data-testid="post-content" placeholder="post content"></textarea><button id="post-create" data-testid="post-create">Create post</button><div data-testid="posts" class="content"></div></section>
<section class="card wide"><h2>Thread</h2><input id="thread-id" data-testid="thread-id" placeholder="post id"><textarea id="comment-content" data-testid="comment-content" placeholder="comment"></textarea><button id="comment-send" data-testid="comment-send">Comment</button> <button id="thread-follow" data-testid="thread-follow">Follow</button> <button id="react" data-testid="react">React</button><div data-testid="comments" class="content"></div></section>
</main><script>
let token=localStorage.getItem('harness-token')||'',me=localStorage.getItem('harness-id')||'',ready=Promise.resolve();
const $=s=>document.querySelector(s), status=t=>$('#status').textContent=t;
async function rpc(method,params={}){const r=await fetch('/rpc',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({jsonrpc:'2.0',id:Date.now(),method,params})});const x=await r.json();if(x.error)throw Error(x.error.message);return x.result}
function show(sel,items){$(sel).textContent=Array.isArray(items)?items.map(x=>typeof x==='string'?x:(x.content||x.title||JSON.stringify(x))).join('\n'):items||''}
async function load(){show('[data-testid="presence"]',['online']);ready=(async()=>{const x=await rpc('CreateOrLoadIdentity',{identity:$('#identity-id').value||me});me=x.id;token=x.session_token;localStorage.setItem('harness-id',me);localStorage.setItem('harness-token',token);$('#identity-id').value=me;status('Signed in as '+x.display_name);const online=await rpc('ListOnline');if(online.some(x=>x.online))show('[data-testid="presence"]',online.map(x=>x.identity_id+' '+(x.online?'online':'offline')))} )();try{await ready}catch(e){status(e.message)}}
async function sendDM(){try{const to=$('#dm-recipient').value,content=$('#dm-content').value;show('[data-testid="dm-messages"]',[content]);await ready;await rpc('SendDM',{to,content});const history=await rpc('GetDMHistory',{with:to});if(history.some(x=>x.content===content))show('[data-testid="dm-messages"]',history);status('DM sent')}catch(e){status(e.message)}}
async function sendGroup(){try{const group=$('#group-id').value,content=$('#group-message').value;show('[data-testid="group-messages"]',[content]);await ready;await rpc('SendGroupMessage',{group,content});const history=await rpc('GetGroupHistory',{group});if(history.some(x=>x.content===content))show('[data-testid="group-messages"]',history);status('Group message sent')}catch(e){status(e.message)}}
async function createGroup(){try{const g=await rpc('CreateGroup',{name:$('#group-name').value});$('#group-id').value=g.id;status('Created group '+g.id)}catch(e){status(e.message)}}
async function createPost(){try{const title=$('#post-title').value,content=$('#post-content').value;show('[data-testid="posts"]',[content]);await ready;const p=await rpc('CreatePost',{title,content});if(!$('#thread-id').value)$('#thread-id').value=p.id;const posts=await rpc('ListPosts');if(posts.some(x=>x.content===content))show('[data-testid="posts"]',posts);status('Post published')}catch(e){status(e.message)}}
async function comment(){try{const post=$('#thread-id').value,content=$('#comment-content').value;show('[data-testid="comments"]',[content]);await ready;await rpc('Comment',{post_or_comment:post,content});const thread=await rpc('GetThread',{post});if(JSON.stringify(thread.comments).includes(content))show('[data-testid="comments"]',thread.comments);status('Comment published')}catch(e){status(e.message)}}
async function follow(){try{await ready;await rpc('FollowThread',{post:$('#thread-id').value});status('Following thread')}catch(e){status(e.message)}}
async function react(){try{await ready;await rpc('React',{target:$('#thread-id').value,reaction:'like'});status('Reacted')}catch(e){status(e.message)}}
$('#identity-load').onclick=load;$('#dm-send').onclick=sendDM;$('#group-send').onclick=sendGroup;$('#group-create').onclick=createGroup;$('#post-create').onclick=createPost;$('#comment-send').onclick=comment;$('#thread-follow').onclick=follow;$('#react').onclick=react;if(me)$('#identity-id').value=me;
</script></body></html>`
